# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["projects"]

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  showMoreLink = false
  showMoreLinkDest = "projects"
  cardView = true

[article]
  showDate = true
  showAuthor = false
  showHero = true
  heroStyle = "big"
  showBreadcrumbs = true
  showReadingTime = true
  showWordCount = false
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showPagination = true

[list]
  showBreadcrumbs = false
  showCards = true
  cardView = true
  groupByYear = false

[taxonomy]
  showTermCount = true

[term]
  groupByYear = false
  cardView = true
