services:
  hugo:
    image: hugomods/hugo:exts
    container_name: blowfish_portfolio
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    command: server --bind 0.0.0.0 --buildDrafts
    restart: unless-stopped
